<?php
/**
 * Displays the server performance report.
 *
 * This script reads a static HTML file generated by a separate bash script.
 * This is efficient and secure as PHP does not execute any shell commands.
 */

// Define the path to the report file. Using __DIR__ makes it portable.
$reportFile = '/var/www/html/public_html/report.html';

// Check if the report file exists and is readable.
if (file_exists($reportFile) && is_readable($reportFile)) {
    // Set the content type header to HTML
    header('Content-Type: text/html; charset=utf-8');

    // Output the content of the file directly to the browser.
    // readfile() is efficient as it writes the file's content
    // directly to the output buffer without loading it all into memory.
    readfile($reportFile);
} else {
    // Display a user-friendly error message if the file is missing.
    header('HTTP/1.1 500 Internal Server Error');
    echo "<h1>Error: Performance Report Not Found</h1>";
    echo "<p>The performance report file could not be found. Please ensure the generation script (`generate_report.sh`) has been run successfully via its cron job.</p>";
    echo "<p>Expected location: " . htmlspecialchars($reportFile) . "</p>";
}
